### ISSUE TITLE
Add String type and string literal syntax

### ISSUE THREAD

**Issue by aslesarenko** [ScorexFoundation/sigmastate-interpreter#230]
Currently we don't have Strings in the language.
This doesn't allow to create ErgoScript which contains some of the constants of IR.
For example it is not possible to do for Array[T], ProveDlog, DHT, BigInteger, etc.
In particular we cannot have a script which contains specific public keys.

The solution:
- [x] Add usual string literals (#231)
- [x] Add string concatenation + (#231)
- [x] add fromBase64, fromBase58, etc decoding function (#238)
- [x] add PK: String -> Value[SigmaProp] decoding of public keys e.g. `PK("2394083")`
- [ ] add generic `deserialize` function which can only deserialize constants (for security reasons)

**Comment by greenhat** [comment]
@ergomorphic 
> add PK: String -> Value[SigmaProp] decoding of public keys e.g. PK("2394083")
What format is expected here? Hex/baseX/other?

**Comment by ergomorphic** [comment]
@greenhat please consult with @catena2w and @kushti. Probably the format should be the same as public keys are serialized in Ergo (in JSON for example). Or how they are shown in Ergo Explorer, to be able to copy-and-paste them.

**Comment by greenhat** [comment]
@ergomorphic  In the explorer we use Base16. If that's the case for JSON API as well then we can quite safely assume Base16 input in `PK`. But I'd rather encode it in type somehow and don't leave as a convention. 
We already have `fromBase58` and 'fromBase64'. We can add `fromBase16` and make `PK(Array[Byte]): Value[SigmaProp]`. Call site will look more verbose `PK(fromBase16("123"))`. We can called it not `fromBase16' but `fromHex` to save more space. Given that string value will be quite long I don't see a problem.

**Comment by greenhat** [comment]
@ergomorphic 
>add generic `deserialize` function which can only deserialize constants (for security reasons)

What signature does it have? I'm struggling to find one that makes sense.
If we're talking about `deserialize[T](s: String): T', where `s` is a byte array encoded to a string, then why not to put the constant in the code itself?

**Comment by ergomorphic** [comment]
@greenhat we need deserialize from string to be able to put constants of any type in the script. Currently we have literals only for some types in a syntax. How you write in a script a constant of type `Array[Byte]`?
With deserialize we can use String as universal literal. 
Deserialize actually works as compiler intrinsic.
During compilation the compiler checks that value can be deserialized to a given type, otherwise it is a compiler error.
```
val myData = deserialize[(GroupElement, Array[(Int, Byte)])]("sdlkjflksdjfkajsdkfj")
// equivalent alternative
val myData = (deserialize[GroupElement]("klksd"), Array((1, 1.toByte), (2, 2.toByte)))
```
Both ways have pros and cons.

**Comment by greenhat** [comment]
@ergomorphic  
>How you write in a script a constant of type Array[Byte]?

For byte array constants we have `fromX`.

Other constant types seem to be usable in "raw" form in code. Assuming group elements are handled by `PK` of course. Besides that, we have AVL tree and box. Should they be expressable as constants in code?
