### ISSUE TITLE
[planing] Roadmap for upcoming releases

### ISSUE THREAD

**Issue by aslesarenko** [ScorexFoundation/sigmastate-interpreter#595]
Since we have huge #566 PR, here is suggested roadmap for upcoming releases:
- [x] merge #592 and release v3.0.3 (v3.x version series)
- [x] create v3.0.4 
- [x] merge #566 into v3.0.4 and release it (v3.x version series)

Work towards hard-fork
- [x] create v4.0 based on v3.0.4 
- [x] merge into v4.0 all PRs with HF changes
- [ ] merge #612 
- [ ] release v4.0

**Comment by aslesarenko** [comment]
This plan is mostly done, and what is not done, it should be replanned.
