### ISSUE TITLE
[planning] Sigma roadmap 2020

### ISSUE THREAD

**Issue by aslesarenko** [ScorexFoundation/sigmastate-interpreter#629]
# Sigma Roadmap 
This issue will be updated as we go forward with new items and status updates.

## Tasks related to Ergo v3.x
This issues should be resolved before v4.0 release
- [x] Resolve [open issues of v3.x milestone](https://github.com/ScorexFoundation/sigmastate-interpreter/issues?q=is%3Aopen+is%3Aissue+milestone%3Av3.x)
- [x] Merge WIP [PRs into v3.x](https://github.com/ScorexFoundation/sigmastate-interpreter/pulls?q=is%3Aopen+is%3Apr+milestone%3Av3.x)

## Tasks related to Ergo v4.0 (hard-fork release)
- [x] finalize JIT costing EIP-8 (https://github.com/ergoplatform/eips/pull/11)
- [x] finalize HF Activation Protocol EIP-9 (https://github.com/ergoplatform/eips/pull/12)
- [x] implement [all v4.0 issues](https://github.com/ScorexFoundation/sigmastate-interpreter/issues?q=is%3Aopen+is%3Aissue+milestone%3Av4.0)
- [x] finish and merge [all v4.0 PRs](https://github.com/ScorexFoundation/sigmastate-interpreter/pulls?q=is%3Aopen+is%3Apr+milestone%3Av4.0) (if any at the that moment)
- [x] release Sigma v4.0 (use it in Ergo v4.0)

## Tasks related to Ergo v5.0 (soft-fork release)
- [x] Revise already fixed issues of v4.0 branch and merge into `develop` as discussed in #660:
- [x] implement [all v5.0 issues](https://github.com/ScorexFoundation/sigmastate-interpreter/issues?q=is%3Aopen+is%3Aissue+milestone%3Av5.0) 
- [x] finish and merge [all v5.0 PRs](https://github.com/ScorexFoundation/sigmastate-interpreter/pulls?q=is%3Aopen+is%3Apr+milestone%3Av5.0) (if any at the that moment)
- [x] release Sigma v5.0 (use it in Ergo v5.0)

## Documentation
 - [x] ErgoScript documentation is finished  
     - [x] ErgoScript language reference section
 - [x] Finish missing part of ErgoTree spec.tex (Ready for merge PR #643)

**Comment by aslesarenko** [comment]
This roadmap is complete. See the next one for future planning.
